sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: MAxinwei123456
  alioss:
    endpoint:  https://oss-cn-beijing.aliyuncs.com
    bucket-name: ren-yanyu
    region: cn-beijing
  redis:
      host: localhost
      port: 6379
      password: MAxinwei123456
      database: 0
  wechat:
    appid: wx99a07b0011a0431e
    secret: 01710bd766d1b1b910eaff096cb3d16f
# ... existing code ...

store:
  address: "河南省开封市河南大学金明校区东苑公寓"
  max-delivery-distance: 5000
